name: DanielHumm - DairyDoughSupplies [SupplierAPI]

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Logistics-Supplier1-API/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./Logistics-Supplier1-API
          push: false # Push seperately 
          tags: ghcr.io/danhumm/dairydoughsupplies-api:latest
          build-args: |
            PFX_PASSWORDD=${{ secrets.PFX_PASSWORD }}
            DB_CONN_STRING=${{ secrets.CONNECTION_STRING }}
            JWT_SERCRET_KEY=${{ secrets.JWT_SERCRET_KEY }}
            JWT_SERCRET_ISSUER=${{ secrets.JWT_SECRET_ISSUER }}

      - name: Push the Docker image
        run: docker push ghcr.io/danhumm/dairydoughsupplies-api:latest
